In [2]:
import pandas as pd

In [1]:
path = "zips/2018q1"
num_path = path + "/num.txt"
pre_path = path + "/pre.txt"
sub_path = path + "/sub.txt"
tag_path = path + "/tag.txt"

In [3]:
pre = pd.read_csv(pre_path, sep="\t", dtype=str)
sub = pd.read_csv(sub_path, sep="\t", dtype=str)
tag = pd.read_csv(tag_path, sep="\t", dtype=str)
num = pd.read_csv(num_path, sep="\t", dtype=str)

In [8]:
sub["sic"] = pd.to_numeric(sub["sic"], errors="coerce")

salud_count = sub[sub["sic"].between(8000, 8099)].adsh.count()
energia_count = sub[sub["sic"].between(1300, 1399)].adsh.count()


salud_count, energia_count

(np.int64(71), np.int64(254))

In [25]:
for name in list(sub.name):
    if "shell" in name.lower():
        print(name)

ROYAL DUTCH SHELL PLC
SHELL MIDSTREAM PARTNERS, L.P.

In [ ]:
sub[sub["name"] == "SHELL MIDSTREAM PARTNERS, L.P."]

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,period,fy,fp,filed,accepted,prevrpt,detail,instance,nciks,aciks
5840,0001610466-18-000013,1610466,"SHELL MIDSTREAM PARTNERS, L.P.",4610.0,US,TX,HOUSTON,77079,150 N. DAIRY ASHFORD,NaN,...,20171231,2017,FY,20180228,2018-02-27 17:35:00.0,0,1,shlx-20171231.xml,1,NaN

In [7]:
# Todos los datos de la base de datos  num.txt que pertenecen a la empresa Apple del estado contable Q2 2026 (adsh = 0000320193-26-000013)
num[(num["adsh"] == "0000320193-26-000013") & (num["tag"] == "NetIncomeLoss")]

Empty DataFrame
Columns: [adsh, tag, version, ddate, qtrs, uom, segments, coreg, value, footnote]
Index: []